# 
title:        샤인한국어학교(Shine Korean Class)
description:  It is time to shine!
url:          https://yidonghyen.github.io
baseurl:      ShineKorean
repository:   "https://github.com/yidonghyen/ShineKorean"
locale:       ko-KR
